scroll_offset = 6
xdg_open = true
xdg_open_fork = true
use_trash = true
watch_files = true
focus_on_create = true
max_preview_size = 2097152000 # 2MB
[display]
mode = "default"
collapse_preview = true
column_ratio = [1, 4, 3]
show_borders = true
show_hidden = false
show_icons = true
tilde_in_titlebar = true
line_number_style = "absolute"
linemode = "size"
[display.sort]
sort_method = "natural"
case_sensitive = false
directories_first = true
reverse = false
[search]
string_case_sensitivity = "insensitive"
glob_case_sensitivity = "sensitive"
regex_case_sensitivity = "sensitive"
fzf_case_sensitivity = "insensitive"
[cmd_aliases]
[tab]
home_page = "home"
root_page = "root"
