[default_view]
keymap = [

  { keys = ["j"], commands = ["cursor_move_down"] },
  { keys = ["u"], commands = ["cursor_move_up"] },
  { keys = ["J"], commands = ["cursor_move_down 5"] },
  { keys = ["U"], commands = ["cursor_move_up 5"] },
  { keys = ["h"], commands = ["cd .."] },
  { keys = ["k"], commands = ["open"] },

  { keys = ["Q"], commands = ["quit"] },
  { keys = ["H"], commands = ["toggle_hidden"] },
  { keys = ["V"], commands = ["toggle_visual"] },
  { keys = ["escape"], commands = ["escape"] },

  { keys = ["d", "d"], commands = ["delete_files"] },
  { keys = ["y", "y"], commands = ["copy_files"] },
  { keys = ["y", "n"], commands = ["copy_filename"] },
  { keys = ["y", "d"], commands = ["copy_filepath"] },
  { keys = ["p", "p"], commands = ["paste_files"] },
  { keys = ["p", "o"], commands = ["paste_files --overwrite=true"] },

  { keys = ["e"], commands = ["shell nvim %s"] },
  { keys = [":"], commands = [":shell "] },
  { keys = ["/"], commands = [":search_fzf "] },
]
[task_view]
[help_view]
